<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Arnabs-MacBook-Air.local" failures="2" tests="3" name="Login Test Suite" time="36.464" errors="0" timestamp="2025-05-22T17:37:42 IST">
  <testcase classname="testClasses.TC_001_Login" name="login" time="1.7"/>
  <testcase classname="testClasses.TC_login_WrongUserName" name="login" time="10.25">
    <failure type="java.lang.AssertionError" message="Login succeeded or unexpected behavior: ">
      <![CDATA[java.lang.AssertionError: Login succeeded or unexpected behavior: 
at testClasses.TC_login_WrongUserName.login(TC_login_WrongUserName.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="testClasses.TC_login_WrongPassword" name="login" time="10.225">
    <failure type="java.lang.AssertionError" message="Login succeeded or unexpected behavior: Your password is invalid!">
      <![CDATA[java.lang.AssertionError: Login succeeded or unexpected behavior: Your password is invalid!
at testClasses.TC_login_WrongPassword.login(TC_login_WrongPassword.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Login Test Suite -->
